app = "yoshitoroid"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  strategy = "immediate"

[processes]
  app = "node index.js"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]  # 👈 【追加】Fly.ioが怒っていた原因はこれが無かったからです！

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
[mounts]
  source = "data"
  destination = "/data"